const products = [
  { label: "Meat", value: "Meat" },
  { label: "Fish", value: "Fish" },
  { label: "Ground meat", value: "Ground meat" },
  { label: "Chicken", value: "Chicken" },
  { label: "Puff pastry", value: "Puff pastry" },
  { label: "Frozen pizza", value: "Frozen pizza" },
  { label: "Frozen vegetable mix", value: "Frozen vegetable mix" },
  { label: "Hummus", value: "Hummus" },
  { label: "Tahini", value: "Tahini" },
  { label: "Smoked fish", value: "Smoked fish" },
  { label: "Pastrami", value: "Pastrami" },
  { label: "Eggplant salad", value: "Eggplant salad" },
  { label: "Pepper salad", value: "Pepper salad" },
  { label: "Cabbage salad", value: "Cabbage salad" },
  { label: "Halva", value: "Halva" },
  { label: "Bread", value: "Bread" },
  { label: "Pita bread", value: "Pita bread" },
  { label: "Tortillas", value: "Tortillas" },
  { label: "Challah bread", value: "Challah bread" },
  { label: "Rolls", value: "Rolls" },
  { label: "Crackers", value: "Crackers" },
  { label: "Ketchup", value: "Ketchup" },
  { label: "Soy sauce", value: "Soy sauce" },
  { label: "Chili sauce", value: "Chili sauce" },
  { label: "Teriyaki sauce", value: "Teriyaki sauce" },
  { label: "Mayonnaise", value: "Mayonnaise" },
  { label: "Mustard", value: "Mustard" },
  { label: "Vinegar", value: "Vinegar" },
  { label: "Canola oil", value: "Canola oil" },
  { label: "Oatmeal", value: "Oatmeal" },
  { label: "Honey", value: "Honey" },
  { label: "Date syrup", value: "Date syrup" },
  { label: "Muesli", value: "Muesli" },
  { label: "Granola", value: "Granola" },
  { label: "Coffee", value: "Coffee" },
  { label: "Hot chocolate", value: "Hot chocolate" },
  { label: "Baking", value: "Baking" },
  { label: "Flour", value: "Flour" },
  { label: "Cocoa", value: "Cocoa" },
  { label: "Baking powder", value: "Baking powder" },
  { label: "Baking soda", value: "Baking soda" },
  { label: "Dry yeast", value: "Dry yeast" },
  { label: "Sugar", value: "Sugar" },
  { label: "Rice puffs", value: "Rice puffs" },
  { label: "Parchment paper", value: "Parchment paper" },
  { label: "Pastry bags", value: "Pastry bags" },
  { label: "Colored sprinkles", value: "Colored sprinkles" },
  { label: "Coconut", value: "Coconut" },
  { label: "Instant pudding", value: "Instant pudding" },
  { label: "Baby wipes", value: "Baby wipes" },
  { label: "Diapers", value: "Diapers" },
  { label: "Tissues", value: "Tissues" },
  { label: "Toilet paper", value: "Toilet paper" },
  { label: "Paper towels", value: "Paper towels" },
  { label: "Cleaning and disinfecting spray", value: "Cleaning and disinfecting spray" },
  { label: "Floor cleaner", value: "Floor cleaner" },
  { label: "Laundry detergent", value: "Laundry detergent" },
  { label: "Fabric softener", value: "Fabric softener" },
  { label: "Dish soap", value: "Dish soap" },
  { label: "Dish sponge", value: "Dish sponge" },
  { label: "Dishwasher detergent", value: "Dishwasher detergent" },
  { label: "Razor blades", value: "Razor blades" },
  { label: "Wax strips", value: "Wax strips" },
  { label: "Shaving gel and foam", value: "Shaving gel and foam" },
  { label: "Toothpicks", value: "Toothpicks" },
  { label: "Cotton swabs", value: "Cotton swabs" },
  { label: "Dental floss", value: "Dental floss" },
  { label: "Deodorant", value: "Deodorant" },
  { label: "Toothpaste", value: "Toothpaste" },
  { label: "Toothbrush", value: "Toothbrush" },
  { label: "Floor mop", value: "Floor mop" },
  { label: "Cleaning cloths", value: "Cleaning cloths" },
  { label: "Hand sanitizer", value: "Hand sanitizer" },
  { label: "Rice", value: "Rice" },
  { label: "Beans", value: "Beans" },
  { label: "Grits", value: "Grits" },
  { label: "Corn", value: "Corn" },
  { label: "Quinoa", value: "Quinoa" },
  { label: "Bulgur", value: "Bulgur" },
  { label: "Spelt", value: "Spelt" },
  { label: "Wheat", value: "Wheat" },
  { label: "Lentils", value: "Lentils" },
  { label: "Oats", value: "Oats" },
  { label: "Noodles", value: "Noodles" },
  { label: "Pasta", value: "Pasta" },
  { label: "Flakes", value: "Flakes" },
  { label: "Couscous", value: "Couscous" },
  { label: "Canned corn", value: "Canned corn" },
  { label: "Canned tuna", value: "Canned tuna" },
  { label: "Canned sardines", value: "Canned sardines" },
  { label: "Canned peas", value: "Canned peas" },
  { label: "Canned olives", value: "Canned olives" },
  { label: "Canned pickles", value: "Canned pickles" },
  { label: "Canned fruit", value: "Canned fruit" },
  { label: "Canned beans", value: "Canned beans" },
  { label: "Tomato paste", value: "Tomato paste" },
  { label: "Canned hummus", value: "Canned hummus" },
  { label: "Canned mushrooms", value: "Canned mushrooms" },
  { label: "Matza", value: "Matza" },
  { label: "20-piece candle pack", value: "20-piece candle pack" },
  { label: "Garbage bags - 100 bags", value: "Garbage bags - 100 bags" },
  { label: "Sandwich bags - 50 bags", value: "Sandwich bags - 50 bags" },
];
  
  export default products;
  